name: cypress testing
on: workflow_dispatch
jobs:
  first-job: 
    runs-on: ubuntu-latest
    steps:
      - name: downloading repo
        uses: actions/checkout@v3
      - name: cypress
        uses: cypress-io/github-action@v5.0.0
        with:
          browser: chrome
          headless: true
          
