name: cypress testing
on: workflow_dispatch
jobs:
  first-job: 
    runs-on: ubuntu-latest
    steps:
      - name: downloading repo
        uses: actions/checkout@v3
      - name: Install Dependencies
        run: npm ci
      - name: testing
        run: npm test
